### ISSUE TITLE
Help with tag ids

### ISSUE THREAD

**Issue by estebanlopeza** [alexgorbatchev/jquery-textext#42]
In first place, I apologize if this is not the right place to make a question regarding the plugin, but I'm really stuck. 
I need to know if the plugin can handle some kind of tag identificator. 

I'm using the ajax plugin to bring the suggestions (just the tags) and it works perfectly, but when I try to return a json element with "key:value" pairs, it stops working.

So, my question is if there's a way to work with tag ids.

Thanks in advance and sorry for my bad english.

**Comment by alexgorbatchev** [comment]
You can do this with ItemManager http://textextjs.com/manual/itemmanager.html

**Comment by muhammedck** [comment]
@alexgorbatchev  I spent much time on manual page and tried to figure out but I couldn't. 
Same problem with @estebanlopeza... At least one simple example will help everyone.

Posting different value rather than selected item will be useful. Can you please give an example?
[
   { "key1" : 'value1' },
   { "key2" : 'value2' },
   { "key3" : 'value3' },  
   …
   ...
   ...  
]

**Comment by iambibhas** [comment]
@alexgorbatchev to achieve this even with a custom `ItemManager` you need to make the list of items available to `stringToItem()` somehow.
